services:
  firestarr-app:
    image: firestarr-app
    build:
      context: .
      target: firestarr-app
      dockerfile: .docker/Dockerfile
      args:
        VERSION: ${VERSION}
        USERNAME: ${USERNAME}
        USER_ID: ${USER_ID}
      tags:
        - firestarr-app:${VERSION}
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - ./firestarr_data:/appl/data
      - ./firestarr_data/sims:/appl/data/sims
    env_file:
      - .env
