services:
  firestarr-app:
    container_name: firestarr-app
    image: ghcr.io/cwfmf/firestarr:dev-0.9.5.4

    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - ./firestarr_data:/appl/data
      - ./firestarr_data/sims:/appl/data/sims
    env_file:
      - .env
