import { FireModelId } from './FireModel.js';
import { SpatialGeometry } from './SpatialGeometry.js';

/**
 * Branded type for ModelResult IDs
 */
declare const ModelResultIdBrand: unique symbol;
export type ModelResultId = string & { readonly [ModelResultIdBrand]: typeof ModelResultIdBrand };

/**
 * Creates a ModelResultId from a string
 */
export function createModelResultId(id: string): ModelResultId {
  if (!id || id.trim().length === 0) {
    throw new Error('ModelResultId cannot be empty');
  }
  return id as ModelResultId;
}

/**
 * Types of output that a fire model can produce
 */
export enum OutputType {
  /** Burn probability raster (0-1 values) */
  Probability = 'probability',
  /** Fire perimeter at a point in time */
  Perimeter = 'perimeter',
  /** Fire intensity grid (kW/m) */
  Intensity = 'intensity',
  /** Rate of spread grid (m/min) */
  RateOfSpread = 'rate_of_spread',
  /** Flame length grid (m) */
  FlameLength = 'flame_length',
  /** Arrival time grid (hours from ignition) */
  ArrivalTime = 'arrival_time',
  /** Crown fraction burned grid (0-1) */
  CrownFractionBurned = 'crown_fraction_burned',
}

/**
 * Output format types
 */
export enum OutputFormat {
  GeoJSON = 'geojson',
  GeoTIFF = 'geotiff',
  Shapefile = 'shapefile',
  KML = 'kml',
}

/**
 * Metadata about a model result
 */
export interface ResultMetadata {
  /** Time offset from simulation start (hours) */
  readonly timeOffsetHours?: number;
  /** Probability threshold used for contour generation */
  readonly probabilityThreshold?: number;
  /** Coordinate reference system (EPSG code) */
  readonly crs?: string;
  /** Resolution in meters (for raster outputs) */
  readonly resolution?: number;
  /** Area in hectares */
  readonly areaHectares?: number;
  /** Statistics about the output */
  readonly statistics?: {
    min?: number;
    max?: number;
    mean?: number;
    stdDev?: number;
  };
  /** Path to raw output file */
  readonly filePath?: string;
  /** Additional custom metadata */
  readonly [key: string]: unknown;
}

/**
 * Properties for creating a ModelResult
 */
export interface ModelResultProps {
  readonly id: ModelResultId;
  readonly fireModelId: FireModelId;
  readonly outputType: OutputType;
  readonly format: OutputFormat;
  readonly geometry?: SpatialGeometry;
  readonly metadata?: ResultMetadata;
  readonly createdAt?: Date;
}

/**
 * Domain entity representing output from a fire model execution.
 *
 * Model results capture the various outputs generated by fire simulation,
 * including probability maps, perimeters, and intensity grids.
 */
export class ModelResult {
  /** Unique identifier for this result */
  readonly id: ModelResultId;

  /** Reference to the parent fire model */
  readonly fireModelId: FireModelId;

  /** Type of output this represents */
  readonly outputType: OutputType;

  /** Format of the output data */
  readonly format: OutputFormat;

  /** Geometry of the result (for vector outputs like perimeters) */
  readonly geometry: SpatialGeometry | null;

  /** Additional metadata about the result */
  readonly metadata: ResultMetadata;

  /** When this result was created */
  readonly createdAt: Date;

  constructor(props: ModelResultProps) {
    this.id = props.id;
    this.fireModelId = props.fireModelId;
    this.outputType = props.outputType;
    this.format = props.format;
    this.geometry = props.geometry ?? null;
    this.metadata = props.metadata ?? {};
    this.createdAt = props.createdAt ?? new Date();
  }

  /**
   * Check if this result has geometry data
   */
  hasGeometry(): boolean {
    return this.geometry !== null;
  }

  /**
   * Check if this is a raster output type
   */
  isRaster(): boolean {
    return [
      OutputType.Probability,
      OutputType.Intensity,
      OutputType.RateOfSpread,
      OutputType.FlameLength,
      OutputType.ArrivalTime,
      OutputType.CrownFractionBurned,
    ].includes(this.outputType);
  }

  /**
   * Check if this is a vector output type
   */
  isVector(): boolean {
    return this.outputType === OutputType.Perimeter;
  }

  /**
   * Gets the time offset in hours (if available)
   */
  getTimeOffsetHours(): number | null {
    return this.metadata.timeOffsetHours ?? null;
  }

  /**
   * Gets the area in hectares (if available)
   */
  getAreaHectares(): number | null {
    return this.metadata.areaHectares ?? null;
  }

  /**
   * Creates a display name for this result
   */
  getDisplayName(): string {
    const typeNames: Record<OutputType, string> = {
      [OutputType.Probability]: 'Burn Probability',
      [OutputType.Perimeter]: 'Fire Perimeter',
      [OutputType.Intensity]: 'Fire Intensity',
      [OutputType.RateOfSpread]: 'Rate of Spread',
      [OutputType.FlameLength]: 'Flame Length',
      [OutputType.ArrivalTime]: 'Arrival Time',
      [OutputType.CrownFractionBurned]: 'Crown Fraction Burned',
    };

    let name = typeNames[this.outputType];

    if (this.metadata.timeOffsetHours !== undefined) {
      name += ` (${this.metadata.timeOffsetHours}h)`;
    }

    if (this.metadata.probabilityThreshold !== undefined) {
      name += ` @ ${(this.metadata.probabilityThreshold * 100).toFixed(0)}%`;
    }

    return name;
  }

  /**
   * Creates a new ModelResult with updated metadata
   */
  withMetadata(metadata: ResultMetadata): ModelResult {
    return new ModelResult({
      id: this.id,
      fireModelId: this.fireModelId,
      outputType: this.outputType,
      format: this.format,
      geometry: this.geometry ?? undefined,
      metadata: { ...this.metadata, ...metadata },
      createdAt: this.createdAt,
    });
  }

  /**
   * Creates a new ModelResult with geometry
   */
  withGeometry(geometry: SpatialGeometry): ModelResult {
    return new ModelResult({
      id: this.id,
      fireModelId: this.fireModelId,
      outputType: this.outputType,
      format: this.format,
      geometry,
      metadata: this.metadata,
      createdAt: this.createdAt,
    });
  }
}
